# values.yaml

image:
  repository: quay.io/keycloak/keycloak-operator
  tag: "25.0.5"
  pullPolicy: Always

serviceAccount:
  create: true
  name: keycloak-operator

rbac:
  create: true

resources: {}

replicaCount: 1

labels: {}

annotations: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  KUBERNETES_NAMESPACE:
    fieldRef:
      fieldPath: metadata.namespace
  RELATED_IMAGE_KEYCLOAK: "quay.io/keycloak/keycloak:25.0.5"

probes:
  livenessProbe:
    httpGet:
      path: /q/health/live
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 3

  readinessProbe:
    httpGet:
      path: /q/health/ready
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 3

  startupProbe:
    httpGet:
      path: /q/health/started
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 3

namespace: keycloak
