apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak-operator.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
  annotations:
    {{- include "keycloak-operator.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "keycloak-operator.name" . }}