{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "keycloak-operator.labels" . | nindent 4 }}
  annotations:
    {{- include "keycloak-operator.annotations" . | nindent 4 }}
{{- end }}